use_default_settings: true

general:
  debug: false
  instance_name: "My SearXNG"

server:
  secret_key: "change-this-secret-key"
  bind_address: "0.0.0.0"
  port: 8080

search:
  safe_search: 0

redis:
  url: false

outgoing:
  request_timeout: 10.0

engines:
  - name: duckduckgo
    disabled: false
