use_default_settings: true

general:
  debug: false
  instance_name: "My SearXNG"

server:
  secret_key: "change-this-secret-key"
  bind_address: "0.0.0.0"
  port: 8080
  public_instance: false
  limiter: false

search:
  safe_search: 0

valkey:
  url: redis://default:${{REDIS_PASSWORD}}@redis.railway.internal:6379

outgoing:
  request_timeout: 10.0

engines:
  - name: duckduckgo
    disabled: false

  - name: ahmia
    disabled: true

  - name: torch
    disabled: true
